### ISSUE TITLE
2FA - migrating from 3.3.3 to 3.4.0

### ISSUE THREAD

**Issue by kuba-lilz** [Flask-Middleware/flask-security#340]
According to changelog changes around two factor authentication introduced in 3.4.0 are:
- In TWO_FACTOR_ENABLED_METHODS "mail" was changed to "email". "mail" will still be honored if already stored in DB. Also "google_authenticator" is now just "authenticator".
- TWO_FACTOR_SECRET, TWO_FACTOR_URI_SERVICE_NAME, TWO_FACTOR_SMS_SERVICE, and TWO_FACTOR_SMS_SERVICE_CONFIG have all been deprecated in favor of names that are the same for two-factor and unified sign in.

My app is using email 2FA. Everything works as expected in 3.3.3, but when moving to 3.4.0 and addressing
- TWO_FACTOR_ENABLED_METHODS - changing "mail" to "email"
- TWO_FACTOR_SECRET, TWO_FACTOR_URI_SERVICE_NAME ->changing to  SECURITY_TOTP_SECRETS and SECURITY_TOTP_ISSUER

2FA isn't working. When enabling 2FA I can see my POST /two-factor-authentication-setup returns 200, but no TOTP is sent to my email.
Is maybe some additional step required to migrate 2FA from flask-security-too 3.3.3 to 3.4.0?

And as always thank you for the great work on this crucial library.

**Comment by jwag956** [comment]
Thanks for the issue report - you shouldn't have had to change anything since I put in code to take the deprecated configs and 'move' them to the new ones. A copy of your config would be useful.

Also - as you know - when using forms - 200 doesn't really mean anything - you need to look for errors in the form.. so a copy of your returned form data would be useful.

Thanks for checking out 3.4!

**Comment by kuba-lilz** [comment]
So, first for the config - the relevant parts are:
```
SECURITY_TWO_FACTOR: True
SECURITY_TWO_FACTOR_ENABLED_METHODS: ["email"]
```
(please let me know if some other settings would be useful)

Actually you had a good point about looking at content of the form.errors.
We had our own version of the `two_factor_setup.html` template + some javascript ux code that was hiding some errors from me.

Looking at our template code I realized our version of  `two_factor_setup.html` template was passing `mail` field to `TwoFactorSetupForm`, whereas it now accepts `email` field:

```python
#  flask_security/forms.py::493
    setup = RadioField(
        "Available Methods",
        choices=[
            ("email", "Set up using email"),
            (
                "authenticator",
                "Set up using an authenticator app (e.g. google, lastpass, authy)",
            ),
            ("sms", "Set up using SMS"),
            ("disable", "Disable two factor authentication"),
        ],
    )
```

So for the time being I changed back to flask-security's original template and... this showed a surprising error.

```
POST /lilzgauge/two-factor-authentication-setup HTTP/1.1 500
flask_security/decorators.py", line 400, in decorated
return fn(*args, **kwargs)
flask_security/views.py, line 738, in two_factor_setup
phone_number=user.tf_phone_number,
werkzeug/local.py", line 348, in __getattr__
return getattr(self._get_current_object(), name)
AttributeError: 'User' object has no attribute 'tf_phone_number'
```

It looks like flask-security thinks I'm trying to set up sms 2FA, but that's not in my `SECURITY_TWO_FACTOR_ENABLED_METHODS`, and so my User class doesn't contain 'tf_phone_number' attribute.

Looking at flask_security/views.py::738, where error happened, I see it's inside this piece of code:
```
        if pm == "email" or (pm == "sms" and new_phone):
            msg = user.tf_send_security_token(
                method=pm,
                totp_secret=session["tf_totp_secret"],
                phone_number=user.tf_phone_number,
            )
```
which seems to ask for tf_phone_number if pm == "email", which looks, huh, wrong to me.
Am I missing something?

**Comment by jwag956** [comment]
Nice sleuthing - looks like a bug introduced while I did some refactoring - it used to be that send_security_token took the entire user model - and I changed it to just take the required attributes. That line should probably just be changed to:

phone_number=getattr(user, "tf_phone_number", None).

If that fixes it - let me know and I can turn a quick 3.4.3
(also - make sure you are migrating to 3.4.2 - not 3.4.0).

**Comment by kuba-lilz** [comment]
Thank you for the suggestion. 
For 3.4.0 I got 2FA to work after making abo
- flask_security/views.py::738 for 2FA setup
- flask_security/twofactor.py::184 for issuing TOTP tokens at login

Seems I need to make some more (unrelated) changes to my code to get it to work with 3.4.2, I'll report once I was able to check above 2FA changes with it.

**Comment by jwag956** [comment]
Thanks - I didn't intend to cause so many regressions/incompatibilities - please let me know.

I also found the same issue with views::794 (rescue).

I missed twofactor.py::184 - I have added that to my PR.

As for the differences between 3.4.0 and 3.4.2 - the only one I can think that might cause an issue is the removal of using form._errors (since that has been removed) - but I thought the actual resulting response was the same.

As always - thanks for all the triaging...

**Comment by kuba-lilz** [comment]
Issue I had with 3.4.2 was actually related to #298 / #304 
My acceptance tests were relying on session["user_id"] to contain user id, but in 3.4.2 it contains fs_uniquifier instead.

2FA in 3.4.2 works fine after changing `phone_number=user.tf_phone_number` to `phone_number=getattr(user, "tf_phone_number", None)` where appropriate 👍
